enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
ctrl-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~/.'

ctrl-k = 'focus up'
ctrl-j = 'focus down'
ctrl-h = 'focus left'
ctrl-l = 'focus right'

ctrl-shift-k = 'move-through up'
ctrl-shift-j = 'move-through down'
ctrl-shift-h = 'move-through left'
ctrl-shift-l = 'move-through right'

ctrl-alt-h = 'split horizontal'
ctrl-alt-v = 'split vertical'

ctrl-f = 'fullscreen'

ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

ctrl-1 = 'workspace 1' # web
ctrl-2 = 'workspace 2' # terminal
ctrl-3 = 'workspace 3' # discord
ctrl-4 = 'workspace 4' # media
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

ctrl-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width +50'
j = 'resize height -50'
k = 'resize height +50'
l = 'resize width -50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'org.chromium.Chromium'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'mpv'
run = 'move-node-to-workspace 4'
